trigger:
- "t-jelipscomb/AIChatbotDataPipeline"

pool:
  vmImage: 'windows-latest'

jobs:
  - job: build
    timeoutInMinutes: 360
    steps:
    - checkout: self
      path: dnceng
    - checkout: git://internal/dotnet-arcade
      path: arcade

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11.4'
        addToPath: true
      displayName: 'Install Python'

    #- script: pip install pipreqs --user
     # displayName: 'Install pipreqs'

   # - script: pipreqs d:\a\1\dnceng\src\Microsoft.DncEng.AzureAIChatbot\
    #  displayName: 'Run pipreqs to generate requirements.txt for AzureAIChatbot'

    #- script: pip install -r d:\a\1\dnceng\src\Microsoft.DncEng.AzureAIChatbot\requirements.txt
    #  displayName: 'Install requirements.txt for AzureAIChatbot'

    - task: AzureCLI@2
      displayName: 'Run prepdocs'
      inputs:
        azureSubscription: dd8c2cfc-b9c9-452c-a168-ccd4240ada55
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          cd $(Agent.BuildDirectory)/dnceng/src/Microsoft.DncEng.AzureAIChatbot
          dir