trigger: none

pool:
    name: NetCore1ESPool-Internal
    demands: ImageOverride -equals 1es-windows-2019

jobs:
  - job: build
    steps:
    - checkout: self
      path: dnceng
    - checkout: git://internal/dotnet-arcade
      path: arcade

    - task: UsePythonVersion@0
      displayName: 'Install Python'
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - task: CmdLine@2
      displayName: 'Install Python Packages'
      inputs:
        script: |
         pip install requests
         pip install azure-search-documents
         pip install azure-identity
         pip install tqdm
         pip install data-utils
         pip install Markdown
         pip install tiktoken
         pip install azure-core
         pip install azure-ai-formrecognizer
         pip install bs4
         pip install langchain

    - task: AzureCLI@2
      displayName: 'Run prepdocs'
      inputs:
        azureSubscription: dd8c2cfc-b9c9-452c-a168-ccd4240ada55
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          cd $(Agent.BuildDirectory)/dnceng/src/Microsoft.DncEng.AzureAIChatbot/scripts
          python data_preparation.py --config config.json --njobs=4